version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@165.22.114.59 "git clone git@github.com:sliim35/projectX.git kantu_v2 && cd kantu_v2 && docker-compose up -d --build"
