version: 2
jobs:
  build:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@165.22.114.59 "rm -rf kantu_v2 && git clone git@github.com:sliim35/projectX.git kantu_v2 && cd kantu_v2 && docker-compose up -d --build"
